# Generated by Django 5.2.6 on 2025-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
    ]
